### PR TITLE
GitHub issues

### PR DESCRIPTION
**Pull request by claireinez**
Adding functions that query GitHub API to return issue objects as JSON.
https://github.com/dwyl/tudo/issues/37

While querying the issues, we make another query to the comments url to append the comments to the issues object.
https://github.com/dwyl/tudo/issues/39

### CODE REVIEW

**Comment by claireinez** [comment]
Reread the last comment in https://github.com/dwyl/tudo/issues/37 from @nelsonic so reassigned the PR to him.

@/all Dummy issues data available on this branch in example_issues.json

**Comment by dwyl-dummy** [comment]
@nelsonic Merged with Jack's and Daniel's database work so ready for merging

**Comment by claireinez** [comment]
@nelsonic Merged with Jack's and Daniel's database work so ready for merging

**Comment by nelsonic** [comment]
_Massive_ Example file! :open_mouth: 
Good to go. :+1:

**Pull request merged**
