### PR TITLE
Integration db to render

### PR DESCRIPTION
**Pull request by jrans**
This PR:
- Fixed parsing errors with speech marks to make returned data consistent in fetch issue.
- Fetch issues function that returns issue array to be rendered. _(Note uses github token in env.json which is dwyl summer so username field redundant as always has to be "dwyl-dummy". Will leave to @benjaminlees  to decide what to do with this but feel it should be taken out and hard coded to "dwyl-dummy" for now and later should be passed the username of the person authenticated which should be held in a sate somewhere.)_

Best Wishes,

J

### CODE REVIEW

**Comment by nelsonic** [comment]
@benjaminlees are you busy reviewing this now?

**Comment by nelsonic** [comment]
@jrans is there anything I can do to help with this?

**Comment by nelsonic** [comment]
@benjaminlees hope you're well & having a good weekend! :smiley:
As I understand it, this PR is not 100% complete but since @jrans is busy on another project right now, it makes sense to merge it in and I will pick up where Jack and @Danwhy left off.
Please confirm if you have time to review & merge **_or**_ assign the PR to me so I can do it. thanks!

**Comment by jrans** [comment]
@nelsonic I believe @benjaminlees is in Spain right now hence slow progress. We did a bit more than this pull request on another branch but after Benjee rewrote some of the tests there was a bug with them that I couldn't fix... Hope everything is going well in Portugal and will sort this out as soon as I can but feeel free to merge ahead anyway!

**Comment by nelsonic** [comment]
Ah, didn't realise @benjaminlees was away... makes sense. Spain. #Lucky :wink: 
If you have time at some point for a hangout, please let me know so we can go through any issues which remain. otherwise I'm happy to pick it up. :+1:

**Comment by benjaminlees** [comment]
@nelsonic sorry i am back i have reviewed but it is missing a bit though. should merge if possible though.

**Comment by nelsonic** [comment]
Merging. will tidy today. :+1:

**Pull request merged**
