### PR TITLE
Adds 'no labels' route with working search

### LINKED ISSUE #229: Have an option to show issues with no labels
As a person who values organisation via labels
I want to be able to have an option to see only issues with no labels (often these issues are _actually_ in need of a `help wanted` label)
So that they can be given the appropriate labels

(taking longer than expected. Updated PT to 1d from 2h because of higher complexity than originally perceived.)

### PR DESCRIPTION
**Pull request by finnhodgkin**
Adds:
* an extra seed script that gets all issues with no labels
* github hooks for issues with no labels
* a route for label-less issues
* working search for label-less issues
* tests

The code isn't very dry. Should we be pulling more stuff out to functions / using child templates?

fixes #229 

(sorry it's a bit monolithic)

### CODE REVIEW

**Comment by finnhodgkin** [comment]
Getting a 'no report found to compare against error' from codecov but coverage is still 100%.

**Review by samhstn — APPROVED** [review]
Great work guys. Code looks really nice.

I think [here](https://github.com/dwyl/tudo/blob/ee4dd678bb3e8dfe72160a82be39e8fc1a3b417e/priv/repo/seeds.exs#L12), I would have probably looked to edit this portion of code rather than writing an additional `get_all_issues` function.

Do you think we need to keep the `get_help_wanted_issues` function any more? When populating our database now, I don't think we care about this filtering.

When I was writing the `hook_controller_test.exs` file, I remember thinking that it was getting a little long. I think it's now getting a little too long. At some point in the next week or so we could start thinking of a way to make this nicer to work with.

It looks like this should all work though 👍

**Comment by ZooeyMiller** [comment]
@shouston3 Most of those changes have now been implemented :+1: we still need to tidy up `hook_controller_test.exs` but I feel that can be a separate PR.

**Review by samhstn — APPROVED** [review]
Looks good

**Pull request merged**
