### PR TITLE
GitHub issues api

### PR DESCRIPTION
**Pull request by jrans**
This pull request:
- We have provided a method to retrieve all issues assigned to a user based on their Github access token.
- 100% test coverage.
- Boilerplate for env.json found in read me.
- Example issue object stored at root of directory for peoples reference.
- Read me update explaining our changes.
- Refactored render code to be more modularised and merged our different server files.

Best Wishes,

Claire, Daniel, Jack, Natalia

### CODE REVIEW

**Comment by nelsonic** [comment]
@jrans please update the description to explain exactly what this PR adds to the project.
if in doubt, see: https://twitter.com/nelsonic/status/621984170353524736

**Comment by NataliaLKB** [comment]
Will get this done tonight: #17

**Comment by NataliaLKB** [comment]
#17 done, but needs to be merged in to this branch.

**Comment by jrans** [comment]
@iteles  updated description, please review changes and merge PR! Important for other teams to proceed as changes made to server.
Thank you!

**Comment by besarthoxhaj** [comment]
Done!

**Pull request merged**
