### PR TITLE
runs through OAuth flow for github

### PR DESCRIPTION
**Pull request by rjmk**
We do have full coverage; waiting on a redis login handler to complete the login

### CODE REVIEW

**Comment by nelsonic** [comment]
Sweet! :lollipop: 
Ok. we _Really_ need to fix the CodeShip build.
Lets take a look at this this afternoon when we get back from lunch!

**Comment by rjmk** [comment]
:+1:

**Comment by nelsonic** [comment]
tests-pass-100-percent
Travis is _not_ cooperating! https://travis-ci.org/dwyl/tudo/builds/77578540

**Comment by nelsonic** [comment]
@iteles please review/merge. thanks.

**Pull request merged**
