### PR TITLE
Adding functionality to riot

### PR DESCRIPTION
**Pull request by iteles**
This pull request adds functionality into our Riot code.
- Pulls hardcoded data into `issues.tag`

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles what is still going to be added to this PR? I would like to pick up the :flashlight: and continue the mission!

**Comment by iteles** [comment]
@nelsonic We were just doing as much to get the data hooked up from redid as possible. But seeing as dwylsummer has finished, we should merge this in and call it a starting point :)

**Comment by nelsonic** [comment]
@rjmk Given that you know the code the best, please review/merge. thanks!

**Comment by rjmk** [comment]
:+1:

**Pull request merged**
